using WX.B2C.User.Verification.Configuration.Models;

namespace WX.B2C.User.Verification.Configuration.Seed
{
    internal static class Regions
    {
        public static Region[] Seed =
        {
            new()
            {
                Name = "EEA",
                Countries = new []
                {
                    "AD",
                    "AT",
                    "BE",
                    "BG",
                    "HR",
                    "CY",
                    "CZ",
                    "DK",
                    "EE",
                    "FI",
                    "FR",
                    "DE",
                    "GI",
                    "GR",
                    "HU",
                    "IS",
                    "IE",
                    "IT",
                    "LV",
                    "LI",
                    "LT",
                    "LU",
                    "MT",
                    "MC",
                    "ME",
                    "NL",
                    "NO",
                    "PL",
                    "PT",
                    "RO",
                    "SK",
                    "SI",
                    "ES",
                    "SE",
                    "CH",
                    "GB"
                }
            },
            new()
            {
                Name = "RoW",
                Countries = new []
                {
                    "AX",
                    "AL",
                    "AG",
                    "AR",
                    "AM",
                    "AW",
                    "BH",
                    "BB",
                    "BZ",
                    "BJ",
                    "BM",
                    "BT",
                    "BF",
                    "KH",
                    "CM",
                    "KY",
                    "CL",
                    "CO",
                    "CK",
                    "CR",
                    "DJ",
                    "DM",
                    "DO",
                    "EC",
                    "SV",
                    "FO",
                    "FJ",
                    "GA",
                    "GE",
                    "GD",
                    "GT",
                    "GG",
                    "HN",
                    "IM",
                    "IL",
                    "JM",
                    "JE",
                    "KZ",
                    "KE",
                    "KW",
                    "KG",
                    "LS",
                    "MW",
                    "MY",
                    "ML",
                    "MR",
                    "MX",
                    "MD",
                    "MS",
                    "NA",
                    "NI",
                    "NE",
                    "NG",
                    "NF",
                    "OM",
                    "PA",
                    "PY",
                    "PE",
                    "PR",
                    "QA",
                    "KN",
                    "LC",
                    "VC",
                    "WS",
                    "TJ",
                    "TZ",
                    "TG",
                    "TM",
                    "TC",
                    "TV",
                    "AE",
                    "UZ",
                    "VG",
                    "ZM",
                    "RU"
                }
            },
            new()
            {
                Name = "APAC",
                Countries = new []
                {
                    "AU",
                    "HK",
                    "KR",
                    "NZ",
                    "PH",
                    "SG",
                    "TW",
                    "TH",
                    "VN"
                }
            },
            new()
            {
                Name = "Global",
                Countries = new []
                {
                    "BA",
                    "BN",
                    "BR",
                    "CA",
                    "DZ",
                    "ID",
                    "IN",
                    "MA",
                    "NP",
                    "PK",
                    "TR",
                    "UA",
                    "XK",
                    "ZA",
                    "US"
                }
            }
        };
    }
}