// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WX.B2C.User.Verification.IpStack.Client
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for IpStackApiClient.
    /// </summary>
    public static partial class IpStackApiClientExtensions
    {
            /// <summary>
            /// The ipstack's primary endpoint is called Standard Lookup and is used to
            /// look up single IPv4 or IPv6 addresses.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='ipAddress'>
            /// Any IPv4 or IPv6 address; you can also enter a domain URL to have ipstack
            /// resolve the domain to the underlying IP address.
            /// </param>
            /// <param name='fields'>
            /// Set to your preferred output field(s) according to the Specify Output
            /// Fields section. (https://ipstack.com/documentation#fields).
            /// </param>
            /// <param name='hostname'>
            /// Set to 1 to enable Hostname Lookup.
            /// (https://ipstack.com/documentation#hostname).
            /// </param>
            /// <param name='security'>
            /// Set to 1 to enable the Security module.
            /// (https://ipstack.com/documentation#security).
            /// </param>
            /// <param name='language'>
            /// Set to a 2-letter language code according to the Specify Output Language
            /// section to change output language.
            /// </param>
            /// <param name='callback'>
            /// Specify a JSONP callback function name according to the JSONP Callbacks
            /// section.
            /// </param>
            /// <param name='output'>
            /// Set to json or xml to choose between output formats.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IpAddressDetails> LookupAsync(this IIpStackApiClient operations, string ipAddress, string fields = default(string), bool? hostname = default(bool?), bool? security = default(bool?), string language = default(string), string callback = default(string), string output = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.LookupWithHttpMessagesAsync(ipAddress, fields, hostname, security, language, callback, output, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// The ipstack's endpoint to request data for multiple IPv4 or IPv6 addresses
            /// at the same time.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='ipAddresses'>
            /// A comma-separated list of IPv4 or IPv6 addresses; you can also enter a
            /// domain URLs to have ipstack resolve the domains to their underlying IP
            /// addresses. (Maximum allowed values: 50)
            /// </param>
            /// <param name='fields'>
            /// Set to your preferred output field(s) according to the Specify Output
            /// Fields section. (https://ipstack.com/documentation#fields).
            /// </param>
            /// <param name='hostname'>
            /// Set to 1 to enable Hostname Lookup.
            /// (https://ipstack.com/documentation#hostname).
            /// </param>
            /// <param name='security'>
            /// Set to 1 to enable the Security module.
            /// (https://ipstack.com/documentation#security).
            /// </param>
            /// <param name='language'>
            /// Set to a 2-letter language code according to the Specify Output Language
            /// section to change output language.
            /// </param>
            /// <param name='callback'>
            /// Specify a JSONP callback function name according to the JSONP Callbacks
            /// section.
            /// </param>
            /// <param name='output'>
            /// Set to json or xml to choose between output formats.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<IpAddressDetails>> BulkLookupAsync(this IIpStackApiClient operations, IList<string> ipAddresses, string fields = default(string), bool? hostname = default(bool?), bool? security = default(bool?), string language = default(string), string callback = default(string), string output = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.BulkLookupWithHttpMessagesAsync(ipAddresses, fields, hostname, security, language, callback, output, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
