// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WX.B2C.User.Verification.IpStack.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// An object containing connection-related data.
    /// </summary>
    public partial class Connection
    {
        /// <summary>
        /// Initializes a new instance of the Connection class.
        /// </summary>
        public Connection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Connection class.
        /// </summary>
        /// <param name="asn">Autonomous System Number associated with the IP.
        /// (https://www.techopedia.com/definition/26871/autonomous-system-number-asn)</param>
        /// <param name="isp">Name of the ISP associated with the IP.</param>
        public Connection(double? asn = default(double?), string isp = default(string))
        {
            Asn = asn;
            Isp = isp;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets autonomous System Number associated with the IP.
        /// (https://www.techopedia.com/definition/26871/autonomous-system-number-asn)
        /// </summary>
        [JsonProperty(PropertyName = "asn")]
        public double? Asn { get; set; }

        /// <summary>
        /// Gets or sets name of the ISP associated with the IP.
        /// </summary>
        [JsonProperty(PropertyName = "isp")]
        public string Isp { get; set; }

    }
}
