// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace WX.B2C.User.Verification.IpStack.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// An object containing security-related data.
    /// </summary>
    public partial class ErrorDetails
    {
        /// <summary>
        /// Initializes a new instance of the ErrorDetails class.
        /// </summary>
        public ErrorDetails()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ErrorDetails class.
        /// </summary>
        /// <param name="code">Error code</param>
        /// <param name="type">Error type. For example monthly_limit_reached.
        /// Possible values include: '404_not_found', 'missing_access_key',
        /// 'invalid_access_key', 'inactive_user', 'invalid_api_function',
        /// 'usage_limit_reached', 'function_access_restricted',
        /// 'https_access_restricted', 'invalid_fields', 'too_many_ips',
        /// 'batch_not_supported_on_plan'</param>
        /// <param name="info">Error description.</param>
        public ErrorDetails(int code = default(int), ErrorType type = default(ErrorType), string info = default(string))
        {
            Code = code;
            Type = type;
            Info = info;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets error code
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public int Code { get; private set; }

        /// <summary>
        /// Gets error type. For example monthly_limit_reached. Possible values
        /// include: '404_not_found', 'missing_access_key',
        /// 'invalid_access_key', 'inactive_user', 'invalid_api_function',
        /// 'usage_limit_reached', 'function_access_restricted',
        /// 'https_access_restricted', 'invalid_fields', 'too_many_ips',
        /// 'batch_not_supported_on_plan'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public ErrorType Type { get; private set; }

        /// <summary>
        /// Gets error description.
        /// </summary>
        [JsonProperty(PropertyName = "info")]
        public string Info { get; private set; }

    }
}
